### ISSUE TITLE
localhost.direct TLS certificate is revoked

### ISSUE THREAD

**Issue by aldipower** [reboot-dev/reboot#6]
Firefox is my main dev browser. Connecting to `https://dev.localhost.direct:9991` worked without a hassle the last weeks. Today I encountered an `SEC_ERROR_REVOKED_CERTIFICATE`. Firefox rendered unable to connect. Chrome works though.

The difference between Firefox and Chrome is, Firefox does OCSP validation checks on the certificate, Chrome does not.
https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol

If I turn off OCSP in Firefox, it works again (a search after "ocsp" on the settings page). But this is not ideal, because it lowers my security and others, facing the same problem, probably do not know about this fix at all.

It seems the localhost.direct certificates got revoked on the OCSP validation servers or Firefox enabled OCSP silently after an update, but then we still have problem with the certificate.

Quick-fixes:
* Turn off OCSP in the browser (not so good)

My thoughts about this in the longer run:
* Allow non-TLS insecure connections in the development environment. 

This also would allow me to define my own hostname, because there is no need for a certificate on a specific host!

Would love to hear more pro arguments for TLS in dev envs. 
Yes, development is closer to production with TLS enabled. And I can use the same cookie policy (secure-cookie-only), which is also good.

* If we want to stay with TLS in dev, we should issue our own certificate to get control back.

We should not rely on an unpaid third-party hobbyist certificate for something like Reboot!
I do not want to offend [Nova Altesse](https://upinel.com/). It is a very friendly move to make such a certificate. Thanks.
Imho it makes sense for own setups in local development. But we should definitely not ship this with our Docker image to others.

**Comment by rjhuijsman** [comment]
This is now affecting Chrome also. We're working on releasing a fix.

In the meantime, Chrome's error can be bypassed.
 1. Navigate to this page: https://dev.localhost.direct:9991/__/reboot/call - you should see an error saying the certificate is revoked.
 2. Type `thisisunsafe` (blindly; there's no text box).

**Comment by stuhood** [comment]
This was fixed in the `0.19.0` release by switching to using `http` by default for `rsm dev`, which avoids the need for SSL.

We will fast-follow the fix for this issue to improve the experience of:
* discovering that you might _actually_ need `https` in dev, because of resource limits imposed by `http` (namely on the number of concurrent connections)
* actually generating and/or providing a certificate to `rsm dev` to re-enable `https`.

Thanks for your patience!

**Comment by aldipower** [comment]
Works perfectly for me. Thank you.
